################ English language ##################
[en]
label = "English"
locale = "en-us"
contentDir = "content/english"
weight = 1

################ Italian language ##################
[it]
label = "Italiano"
locale = "it-it"
contentDir = "content/italian"
weight = 2

################ French language ##################
[fr]
label = "Français"
locale = "fr-fr"
contentDir = "content/french"
weight = 3

################ Spanish language ##################
[es]
label = "Español"
locale = "es-es"
contentDir = "content/spanish"
weight = 4
