############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Links"
url = "/links"
weight = 3

#[[main]]
#name = "Elements"
#url = "/elements"
#weight = 3

#[[main]]
#weight = 4
#name = "Pages"

[[main]]
name = "Blog"
url = "/blog"


[[main]]
parent = "Blog"
name = "Books Readed"
url = "/categories/books/"

[[main]]
parent = "Blog"
name = "Projects "
url = "/categories/projects/"

[[main]]
parent = "Blog"
name = "Thougths"
url = "/categories/thoughts/"

[[main]]
parent = "Blog"
name = "Expriences"
url = "/categories/experiences/"

[[main]]
name = "Tech"
url = "/categories/tech-projects/"

[[main]]
parent = "Tech"
name = "Publications"
url = "/categories/publications/"

[[main]]
parent = "Tech"
name = "Projects"
url = "/categories/tech-projects/"

#[[main]]
#name = "Contact"
#url = "/contact"

#[[main]]
#name = "Categories"
#url = "/categories"


# footer menu
[[footer]]
name = "Vision without action is just a dream, action without vision is just activity"